### ISSUE TITLE
Transfer ownership to emacs-php

### ISSUE THREAD

**Issue by stevenremot** [emacs-php/ede-php-autoload#29]
Following https://github.com/emacs-php/php-mode/issues/235, the ownership of this package will be transfered to the @emacs-php group.

Tasks to perform:

- [x] Move the repository
- [x] Update the MELPA recipe
- [x] Ensure the CI works properly
- [x] Update references to the old repository URL to the new one

I would like to know if you see other tasks to do @zonuexe , either for ownership transferring, or for making it easy for others to contribute.

**Comment by stevenremot** [comment]
PR done on MELPA: https://github.com/melpa/melpa/pull/5716

**Comment by stevenremot** [comment]
The CI build is totally broken, I think I will have to update the way emacs is installed.

**Comment by zonuexe** [comment]
@stevenremot Thanks!

**Comment by stevenremot** [comment]
You're welcome, thanks to YOU @zonuexe, @ejmr !
